jamsocket/plane

.github/workflows/build.yml

Currently, the tags created by metadata extraction aren't used, this fixes that.

Per-package metadata extraction

---

crates/sweeper/src/main.rs

this is... uh... very ugly and probably Very Bad Rust™️

fix container ready bug again - by setting timeout on container request

---

Cargo.lock
Cargo.toml
src/drone/agent/mod.rs
src/drone/cert/mod.rs
src/drone/cli.rs
src/drone/mod.rs
src/logging.rs

Log drone events over NATS

---

Cargo.lock
Cargo.toml
README.md
src/database.rs
src/drone/agent/docker.rs
src/drone/agent/executor.rs
src/drone/proxy/mod.rs
src/messages/agent.rs
src/types.rs

Forward drone logs over NATS

---

.github/workflows/build-test-image.yml

It didn't trigger on the last push to main, this fixes the trigger.

Fix build image workflow trigger

---

README.md

Remove deps.rs badge

---

controller/src/lib.rs

This results in a nicer spawn request log message.

Fix spawn request logging

---

.dockerignore
docker-compose.yml
sample-config/controller.toml
sample-config/drone.toml

Minimal functional docker-compose config

---

drone/src/run.rs

Currently, if a drone ID is not passed in via configuration, one is generated during the planning stage. Enabling tracing requires that the drone ID be known, so we currently defer enabling tracing until after planning. This means that log messages during planning do not appear.
This PR instead ensures that a drone ID exists in the config that gets passed into planning, generating one if necessary. This allows us to enable tracing before planning begins.

Initialize tracing before planning

---

README.md
docs/src/pages/index.mdx

Fix passive voice nit

---

.github/workflows/build-cli-image.yml
.github/workflows/build-controller-image.yml
.github/workflows/build-drone-image.yml
.github/workflows/build-test-image.yml

This probably works, but it's an action so we won't know until we try it.

Add arm64 arch to docker builds

---

Cargo.lock
controller/src/lib.rs
dev/Cargo.toml
dev/tests/dns.rs

Adds a TXT and A record tests. Closes #187.

Basic DNS record tests

---

drone/src/agent/executor.rs

fixes https://github.com/drifting-in-space/plane/issues/193

fix bug and notif for other unhandled errors

---

cli/src/main.rs
core/src/messages/agent.rs
dev/src/util.rs
drone/src/agent/engines/docker/mod.rs
drone/src/agent/engines/docker/util.rs

Adds pull policy to docker executor
(the rebase was a bit far and was confusing me so I just grew a new branch and cherry picked stuff)

Add image pull policy for Docker executor

---

cli/src/main.rs
core/src/messages/agent.rs
dev/src/util.rs
drone/src/agent/engine.rs
drone/src/agent/engines/docker/mod.rs
drone/src/agent/engines/docker/util.rs
drone/src/agent/executor.rs

This PR:
- Allows port and environment variables to be specified on the CLI (#280 by @t-moe)
- Removes the host port bindings from the Docker executor (mentioned by @MyCADDev on discord)

Network port improvements

---

core/src/messages/agent.rs
core/src/messages/scheduler.rs
dev/tests/agent.rs
dev/tests/proxy.rs
dev/tests/scheduler.rs
drone/src/agent/engines/docker/mod.rs
drone/src/config.rs
drone/src/proxy/service.rs

add memory limit opt

---

Cargo.lock
cli/Cargo.toml
cli/src/main.rs
controller/Cargo.toml
controller/src/plan.rs
core/Cargo.toml
core/src/nats_connection.rs
dev/src/resources/nats.rs
drone/Cargo.toml
drone/src/plan.rs

This will enable a drone to operate even if it is restricted to messaging on `cluster.{cluster}.>`
Also bumps version.

Use cluster-based inbox

---

.github/workflows/build-cli-image.yml
.github/workflows/build-controller-image.yml
.github/workflows/build-drone-image.yml
.github/workflows/build-test-image.yml
.github/workflows/clippy.yml

Turns out actions don't have a default runs-on

Add `runs-on` line to workflows.

---

core/src/nats.rs

Validate NATS subject when receiving message

---

cli/src/main.rs
dev-cli.sh

Get list-backends working

---

Cargo.lock
cli/Cargo.toml
controller/Cargo.toml
core/Cargo.toml
core/nats-macros/Cargo.toml
drone/Cargo.toml
metrics/Cargo.toml

Once #385 is landed, we can rebase this PR

version bump 0.3.21

---

controller/src/dns/mod.rs
core/src/state/world_state.rs
dev/tests/proxy.rs
dev/tests/scheduler.rs
drone/src/config.rs
drone/src/plan.rs
drone/src/proxy/mod.rs
sample-config/plane-config/drone.toml

redirects a configured http_port (80 by default) to https using a 308 in the proxy. Plus a test.

Redirect HTTP requests to HTTPS

---

.github/workflows/build-drone-image.yml

ARM builds are being a pain, disable them for now.

Disable arm drone builds

---

controller/Dockerfile
drone/Dockerfile

Disable sccache

---

cli/src/main.rs
controller/src/drone_state.rs
controller/src/lib.rs
controller/src/run.rs
core/src/messages/scheduler.rs
core/src/messages/state.rs
core/src/state/mod.rs
core/src/state/world_state.rs
core/src/types.rs
dev/tests/agent.rs
dev/tests/dns.rs
dev/tests/drone_state.rs
dev/tests/scheduler.rs
drone/src/run.rs
sample-config/dev-config/drone.toml

supersedes  https://github.com/drifting-in-space/plane/pull/425

fix lock acquisition race condition

---

Cargo.toml
cli/src/main.rs
controller/src/lib.rs
dev/tests/cert.rs
dev/tests/scheduler.rs

This is purely the result of running `cargo fmt`. I want to rebase #438 on this so that the diff is easier to read.

Run formatter

---

cli/src/main.rs

Shouldn't break existing behaviour, just allow specifying multiple drones

drone: String -> Vec<String> in plane-cli

---

controller/src/http_server.rs
sample-config/dev-config/controller.toml

Set PORT from HTTP spawn

---

drone/src/agent/engines/docker/util.rs

sometimes docker doesn't send memory_stats.usage. No idea why, but we shouldn't panic when that happens.

avoid panicking in stats stream

---

core/src/nats.rs

This adds unsubscribe and queue group support to TypedNats.
The queue group functionality is necessary for situations where you have more than one process handling messages on a subject (whether for robustness or for availability during zero-downtime deploys), but you want to make sure you only send a given message to a single process.
The unsubscribe allows us to gracefully shut down subscriptions before terminating a subscribe loop.
Ideally, we'd have a `drain()` method on TypedNats, but it doesn't come out-of-the-box in `async_nats` the way it does in `nats`. Adding `unsubscribe()` to the `TypedSubscription` is a good start anyway.

add unsubscribe and queue group support to TypedNats

---

plane2/src/bin/cli.rs
plane2/src/bin/db-cli.rs
plane2/src/client/mod.rs
plane2/src/controller/backend_status.rs
plane2/src/controller/connect.rs
plane2/src/controller/core.rs
plane2/src/controller/drain.rs
plane2/src/controller/drone.rs
plane2/src/controller/proxy.rs
plane2/src/controller/terminate.rs
plane2/src/database/acme.rs
plane2/src/database/backend.rs
plane2/src/database/backend_key.rs
plane2/src/database/connect.rs
plane2/src/database/drone.rs
plane2/src/database/mod.rs
plane2/src/database/node.rs
plane2/src/dns/mod.rs
plane2/src/drone/mod.rs
plane2/src/main.rs
plane2/src/protocol.rs
plane2/src/proxy/cert_manager.rs
plane2/src/proxy/mod.rs
plane2/src/proxy/proxy_connection.rs
plane2/src/types.rs
plane2/tests/common/test_env.rs

See commit messages for descriptions

clusterId -> clusterName, validate cluster name, make https based on port

---

.github/workflows/build-image.yml
.github/workflows/clippy.yml
.github/workflows/rustfmt.yml
.github/workflows/tests.yml

Try to fix build action

---

plane2/src/bin/db-cli.rs
plane2/src/client/mod.rs
plane2/src/client/sse.rs
plane2/src/dns/mod.rs
plane2/src/drone/state_store.rs
plane2/src/drone/wait_backend.rs
plane2/src/heartbeat_consts.rs
plane2/src/lib.rs
plane2/src/main.rs
plane2/src/proxy/cert_manager.rs
plane2/src/proxy/cert_pair.rs
plane2/src/proxy/connection_monitor.rs
plane2/src/proxy/mod.rs
plane2/src/proxy/proxy_service.rs
plane2/src/proxy/rewriter.rs
plane2/src/typed_socket/client.rs
plane2/src/typed_socket/mod.rs
plane2/src/typed_socket/server.rs
plane2/src/util.rs

Misc cleanup, focusing on the Drone in particular:
- More consistency with state vs. status
- Adds some comments
- Remove some unwraps
- Remove some redundant duration conversions
- Simplify `CertManager` data flow

Misc plane2 cleanup

---

plane/src/heartbeat_consts.rs

just fixing the consts in the doc tests

fix doc tests

---

plane/src/drone/docker/commands.rs

The latest rust adds a lint that we don't pass, until now!

Fix new clippy nit

---

docker/quickstart/supervisord.conf
plane/Cargo.toml
plane/src/controller/mod.rs
plane/src/proxy/rewriter.rs

Fixes are described in the commit descriptions

misc fixes

---

plane/src/drone/docker/commands.rs

I found this test flakey when running locally, I think because I'm on an old version of Docker. These changes make it easier to isolate the issue when the test fails.

Clean up resource limit test

---

cli/src/main.rs

The mark-backend-lost command has two issues:
1. The confirmation check fails when entering a `y` + enter.
2. The command doesn't send an UpdateBackendState message, which is needed in order for the WorldState to actually get updated (and for locks held by Lost backends to be released).
This PR fixes that.

fix mark-backend-lost cli command

---

Cargo.lock
plane/Cargo.toml

version bump to 0.4.3

---

plane/src/main.rs
plane/src/proxy/mod.rs
plane/src/proxy/proxy_service.rs

Add --root-redirect-url proxy setting

---

plane/src/drone/backend_manager.rs

The drone is failing to terminate some containers because the containers are already gone. This has the drone failing to ack the termination requests from the controller, leaving us stuck in a loop of failed termination attempts.

dont fail termination if container is already gone

---

plane/src/database/connect.rs

It's possible to check the db and see no lock is held and then fail to insert the backend a few microseconds later because the lock has been taken. In those cases we need to recheck the lock once more and see if we can return the backend with the held lock.
This code change is pretty ugly IMHO, so I'm definitely open to alternatives.

dont 500 when creating backends with already-held keys

---

docs/pages/quickstart-guide.mdx
plane/src/proxy/connection_monitor.rs

I realized the atomics were unnecessary here and possibly leading to correctness problems. This is a move towards simpler, more readable code. I'm still inclined to rewrite this module at some point to make the logic even cleaner.

Connection monitor refactor

---

plane/src/main.rs

Plane already implements EAB internally, this just exposes it on the CLI when running a Proxy.

Expose EAB configuration on proxy CLI

---

plane/src/drone/docker/mod.rs

This uses the built-in Docker API for pruning containers (previously we only used it for images).

Refactor container/image pruning

---

cli/src/main.rs

The cleanup script for plane1 can be pretty chatty. This cuts way back on the number of logs it generates when `--dry-run` is false.

remove extra logs from cli

---

plane/src/controller/mod.rs
plane/src/drone/docker/commands.rs
plane/src/drone/docker/mod.rs
plane/src/types/backend_state.rs

This makes a bunch of ergonomic fixes to logs; comments inline.

Misc logging improvements

---

plane/src/database/backend.rs

Instead of acquiring a connection, just pass the pgpool.

Use pgpool for emit

---

plane/src/controller/mod.rs

Currently, if the heartbeat loop fails (possibly because the DB connection was lost), the controller heartbeat will not be re-sent. This fixes that.

Stop controllers from breaking after a DB restart

---

Cargo.lock
plane/Cargo.toml
plane/plane-dynamic/Cargo.toml
plane/plane-tests/Cargo.toml

I will wait until #679 is merged to cut this version.

Version bump to 0.4.9

---

plane/.sqlx/query-a33f3caa90260ece5326e85584c33030c86cf7c8e3ed773ee7346c108479c0a8.json
plane/plane-tests/tests/backend_actions.rs
plane/plane-tests/tests/backend_lifecycle.rs
plane/plane-tests/tests/backend_status_in_response.rs
plane/plane-tests/tests/drone_pools.rs
plane/plane-tests/tests/reuse_key.rs
plane/plane-tests/tests/subdomains.rs
plane/plane-tests/tests/volume_mounts.rs
plane/src/admin.rs
plane/src/database/connect.rs
plane/src/database/drone.rs
plane/src/types/mod.rs

* [Move pool into SpawnConfig](https://github.com/drifting-in-space/plane/commit/d3420afa8e75946389d2ea64d1c8277821b4e8ef) -- a more natural place for drone pool, alongside cluster.
* [Add function to fetch drone pool by drone id](https://github.com/drifting-in-space/plane/commit/c946ff64370bc980f62d36b43ade678a34e0d754) -- for use in the platform

Tweaks to drone pools

---

docs/pages/plane-api.mdx
plane/plane-tests/tests/backend_actions.rs
plane/plane-tests/tests/backend_lifecycle.rs
plane/plane-tests/tests/backend_status_in_response.rs
plane/plane-tests/tests/common/test_env.rs
plane/plane-tests/tests/drone_pools.rs
plane/plane-tests/tests/reuse_key.rs
plane/plane-tests/tests/subdomains.rs
plane/plane-tests/tests/volume_mounts.rs
plane/src/admin.rs
plane/src/client/mod.rs
plane/src/controller/drone.rs
plane/src/database/connect.rs
plane/src/database/drone.rs
plane/src/drone/command.rs
plane/src/drone/mod.rs
plane/src/proxy/rewriter.rs
plane/src/types/mod.rs

Also remove pool from docs -- pool was mentioned but under the wrong place. We don't elaborate on
other spawn config options, so removing it entirely.

Add DronePoolName type

---

docker/docker-compose.yml
plane/plane-tests/tests/common/resources/database.rs
plane/plane-tests/tests/common/test_env.rs
plane/src/util.rs

Fix Mac IP issue

---

plane/plane-tests/tests/backend_actions.rs
plane/plane-tests/tests/backend_lifecycle.rs
plane/plane-tests/tests/backend_status_in_response.rs
plane/plane-tests/tests/docker_command.rs
plane/plane-tests/tests/drone_pools.rs
plane/plane-tests/tests/metrics.rs
plane/plane-tests/tests/reuse_key.rs
plane/plane-tests/tests/subdomains.rs
plane/plane-tests/tests/volume_mounts.rs
plane/src/admin.rs
plane/src/client/mod.rs
plane/src/controller/connect.rs
plane/src/controller/core.rs
plane/src/database/connect.rs
plane/src/database/mod.rs
plane/src/drone/backend_manager.rs
plane/src/drone/docker/commands.rs
plane/src/drone/docker/mod.rs
plane/src/protocol.rs
plane/src/types/mod.rs

Make executor config generic

---

plane/plane-tests/tests/cert_manager.rs
plane/plane-tests/tests/common/resources/database.rs
plane/plane-tests/tests/common/test_env.rs
plane/plane-tests/tests/docker_command.rs
plane/plane-tests/tests/metrics.rs
plane/src/client/sse.rs
plane/src/drone/backend_manager.rs
plane/src/drone/docker/mod.rs

Part of making runtimes generic (#712)

Generalize pull (now prepare)

---

plane/src/proxy/proxy_service.rs

As we have discussed previously, adding CORS headers on backends is safe now that we use secret connection tokens, so this adds them to both Plane-initiated responses and backend responses.

Add CORS headers to responses

---

plane/src/drone/runtime/docker/mod.rs
plane/src/drone/runtime/mod.rs
plane/src/drone/runtime/unix_socket/mod.rs
plane/src/lib.rs
plane/src/typed_unix_socket/client.rs
plane/src/typed_unix_socket/server.rs
plane/src/types/backend_state.rs

No logic, just sends/receives stuff over a unix socket (as a client) and expects a server to do all the thinking.
Warning: completely untested -- was going to continue with implementing the server side and see how that goes.

Socket based executor client

---

plane/src/proxy/proxy_service.rs

When we debug connection-related issues, it is useful to have a backend id.

Add backend ID to error log

---

plane/src/drone/runtime/docker/mod.rs

Make PLANE_DOCKER_LABEL pub

---

plane/src/typed_unix_socket/client.rs
plane/src/typed_unix_socket/server.rs

Helpful to see the message in context of the error.

Improve typed unix socket logging

---

Cargo.lock
common/Cargo.toml
dynamic-proxy/Cargo.toml
plane/Cargo.toml

Bumps version of crates from 0.5.1 to 0.5.2.

v0.5.2 version bump
