crates/sidecar/src/monitor.rs

I could be way off here, but I wonder if the bug we occasionally see where we don't seem to detect when a container is ready might be caused by a relaxed ordering of the reads / writes for the atomic boolean `ready` value.
Using logs in datadog, I found [a container that had a very long time-to-ready](https://app.datadoghq.com/logs?query=host%3Agke-jamsocket-cluste-jamsocket-cluste-2d01061e-k20z.us-east4-c.c.jamsocket-337914.internal%20service%3Aspawner-sweeper%20container_id%3Ab46f1cd137fdb14deac18014d99bcee7a131bc25a114ce3fd8e2d47524dedd61%20filename%3A0.log&context_event=AQAAAX_b1oFBYbiLPwAAAABBWF9iMW93WUFBQ1Bic3NPa1A1eWdRQUQ&event=AQAAAX_b1oFBYbiLPwAAAABBWF9iMW93WUFBQ1Bic3NPa1A1eWdRQUQ&index=&stream_sort=desc&viz=&from_ts=1648660474090&to_ts=1648660973513&live=false): `c9xhj`. I then …

fix container ready bug

---

.cargo/config.toml
.github/workflows/integration-tests.yml
.github/workflows/unit-tests.yml

PROBLEM:
dev hot-rebuilds currently take ~10s on a 4c8t intel laptop
from circa 2017. (rustc 1.61.0)
SOLUTION:
After switching to mold, this time drops to ~3.5s.
FURTHER INFORMATION:
Profiling via rustc --self-profile reveals that most of the time
for a hot reload comes from linking. mold is a faster linker than
lld or ld.
POSSIBLE IMPROVEMENTS:
Switching to rust nightly (currently 1.63.0) yield further 20-30%
improvements.

config to switch linker to mold for linux target

---

.cargo/config.toml
.dockerignore
.github/workflows/integration-tests.yml
.github/workflows/unit-tests.yml
fast_build.sh

PROBLEM:
as mentioned in 86054, hot-reloads take around 10s, mostly due to
linker.
SOLUTION:
use mold, this time via a fast_build script that sets the necessary
cargo env vars, ensures that mold and clang are installed, and runs
cargo build with the correct path for the mold linker.
POSSIBLE IMPROVEMENTS:
may be a good idea to switch the shell script for a zx script. Also
would be nice if `cargo build` automatically ran fast_build.sh as a
wrapper if the host and profile are correct (ie. linux host, with
dev profile)

Fix fast build

---

src/drone/agent/executor.rs
src/logging.rs
tests/src/test-agent.ts

This logs fields provided in the `metadata` of a backend, both to stdout logs and over NATS.

Log backend metadata

---

Cargo.lock
Cargo.toml
src/drone/agent/executor.rs
src/messages/agent.rs
tests/src/test-agent.ts
tests/src/test-end-to-end.ts
tests/src/util/types.ts

By default, `Duration` serializes to `{secs: number, nsecs: number}`. We don't need the precision of nanoseconds, so just use seconds to serialize.

Cleaner API for duration units

---

src/database.rs
src/database_connection.rs
src/drone/agent/mod.rs
src/drone/cert/mod.rs
src/drone/cli.rs
src/drone/mod.rs
src/drone/proxy/mod.rs
src/lib.rs
src/nats_connection.rs

It's possible for two paths to try creating the db at the same time, which seems to be a source of test flakiness. This PR applies the same approach we use for sharing the NATS connection to sharing the database pool.

Use a mutex to guard initial DB migration

---

src/drone/agent/docker.rs
src/drone/agent/executor.rs
tests/src/test-agent.ts

Instead of just stopping containers, remove them. Should also cut down on spurious warnings about containers not existing.

Ensure that containers are removed

---

drone/src/drone/cert/mod.rs
drone/src/drone/cli.rs
tests/src/test-agent.ts
tests/src/test-cert-refresh.ts
tests/src/test-end-to-end.ts
tests/src/util/id_gen.ts

This is a light refactoring that simplifies data flow of EAB kid/keys. The main thing I am aiming for here are:
- Fuse together EAB key and kid to simplify data flow inside the codebase.
- Handle missing key/kid early so that they are an error at the parse stage.
- Handle base64-decoding early so that it is an error at the parse stage.
I also removed the failure test. In general I like tests of failure cases, but in this case the failure isn't particularly interesting (we're effectively just testing for a non-zero exit code), and the test was causing me other problems with flakiness.

Refactor EAB data flow

---

core/src/logging.rs
core/src/messages/agent.rs
core/src/messages/cert.rs
core/src/messages/logging.rs
core/src/nats.rs
dev/src/util.rs
dev/tests/agent.rs
dev/tests/cert.rs
drone/src/drone/agent/executor.rs
drone/src/drone/agent/mod.rs
drone/src/drone/cert/mod.rs
drone/src/drone/mod.rs

NATS publish permissioning works at the subject glob level: a user can be given rights to publish to subjects that match a specific glob. If the subject refers to a particular resource (e.g., a particular backend or drone), the ID of that resource can be encoded into the subject to limit who has access to that resource.
A listener who is listening on a wildcard needs to ensure that an incoming message refers to the resource in its subject. Otherwise, a writer with permission to publish to any resource could effectively create messages that refer to *any* subject, and have them treated the same by the wildcard subscriber.
One way to do this is for the subscriber to parse the subject, and then check that the value in the message matches the value in the subject. Another way (which avoids …

Refactor Typed NATS wrapper

---

core/src/messages/agent.rs
core/src/messages/cert.rs
core/src/messages/logging.rs
core/src/nats.rs
dev/tests/agent.rs
dev/tests/cert.rs
drone/src/drone/agent/executor.rs
drone/src/drone/agent/mod.rs
drone/src/drone/cert/mod.rs
drone/src/drone/proxy/tls.rs

Draft pr to add backend.:id.terminate. 
I have not yet added the typed-nats checks to ensure the terminate command body refers to the backend_id in the address. (but I don't think that should substantially change anything in what's been written thus far,  just return an error either when `sub.next()` is called or when `msg.value` is accessed

Add backend.:id.terminate nats endpoint

---

core/src/logging.rs
drone/src/drone/agent/docker.rs

PROBLEM: The NanoCPUs setting sets shares of 100 milliseconds of
CPU time. This is bad for setting defaults, since it leads
to degraded performance in bursty workloads.
SOLUTION: Switch to using default CPU_PERIOD of 0.1 seconds with CPU_QUOTA
of 97% of that. This ensures breathing room for spawner.
NOTE:   CPU_PERIOD has a max allowed value of 1 second. It'd be nice if
we could set a longer cpu period. brief investigation suggests
this is a kernel limit, so maybe a thing that can be improved.

remove default NanoCPUs and use CPU_PERIOD with CPU_QUOTA instead

---

controller/src/lib.rs
core/src/messages/agent.rs
core/src/messages/cert.rs
core/src/messages/logging.rs
core/src/messages/mod.rs
core/src/messages/scheduler.rs
core/src/nats.rs
drone/src/drone/agent/mod.rs

This is the first of several refactors under #132 to make the NATS wrapper nicer/safer to work with.
**Remove `Subject`**: `Subject` was only used to describe subjects to publish to, and `SubscribeSubject` was used for subscriptions. It's still useful to have a typed handle to a (possibly wildcard) subject to use for subscriptions, but we recently added a rule that a message should always be sent to a subject deterministically derived from the message itself. That means we no longer have a need for a typed `Subject`; when we want to send a message we just pass the message itself.
**Remove `StreamName`**: `StreamName` was used as a typed handle to the JetStream stream associated with an object. Rather than passing this handle around, we implement a `JetStreamable` trait instead that …

Get rid of Subject type (per #132)

---

controller/src/lib.rs
controller/src/scheduler.rs
core/src/types.rs

This is a pretty straightforward PR; highlights:
- `Scheduler` no longer accesses system time directly; takes it as an argument for ease of unit testing
- `Scheduler` now operates on a per-cluster basis.
- Added some unit tests.
Fixes #146

Add scheduler tests and implement per-cluster scheduling

---

drone/src/agent/mod.rs

This uses jetstream for sending node status messages, which means that an error will be logged if there is an issue with the stream.
Related: #168

Use jetstream for status message

---

core/src/messages/agent.rs

Previously, we would retain all drone status messages in jetstream and replay them. Now we don't.

Limit stream to one message per drone

---

core/src/messages/agent.rs
dev/tests/agent.rs
drone/src/agent/docker.rs
drone/src/agent/executor.rs

this PR moves from the streaming docker_stats api to a polling API, this solves the currently buggy backend_stats messages (throttling doesn't drop messages) and also cleans up the code a bunch since get_stats no longer need return an Option.

move from streaming stats api to polling

---

Cargo.lock
cli/Cargo.toml
cli/src/main.rs
controller/src/lib.rs
core/src/messages/scheduler.rs
core/src/types.rs
dev/src/util.rs
dev/tests/scheduler.rs

Currently, whoever invokes `ScheduleRequest` is responsible for picking a backend. This still allows that behavior, but additionally allows them to leave the backend name as `None` to have a backend name auto-generated.
The caller will still need access to the backend which has been scheduled, so a `backend_id` field is added to `ScheduleResponse`.

Allow scheduler to pick backend name (fixes #182)

---

.github/workflows/build-cli-image.yml
.github/workflows/build-controller-image.yml
.github/workflows/build-drone-image.yml
.github/workflows/build-test-image.yml

`arm64` seems to be breaking the build by causing a timeout at 45(!) minutes.
`paths-ignore` in `build-test-image.yml` is redundant.

Fix github workflows

---

Cargo.lock

I broke the build by force-pushing to our bollard clone. This will all be cleaned up soon when our bollard changes are merged into main.

Update bollard commit hash

---

controller/src/scheduler.rs
core/src/messages/agent.rs
dev/tests/scheduler.rs
drone/src/agent/mod.rs

`CARGO_PKG_VERSION` is [set by cargo at compile time](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates). The Rust [`env` macro](https://doc.rust-lang.org/std/macro.env.html) will read a value at compile time and insert it into the source.
This also removes the `capacity` value from the liveness ping. It was a placeholder that we never used, and probably does not represent how we want to do scheduling.

Report drone version in liveness ping

---

controller/src/lib.rs

I noticed that Plane was creating a Jetstream here when [the equivalent code in the platform](https://github.com/drifting-in-space/p2/blob/main/jamsocket/src/platform/mod.rs#L32-L34) is just using a regular nats subscription. Could this be related?

subscribe to drone status message as a regular subscription - not a jetstream

---

cli/src/main.rs
controller/src/dns/mod.rs
controller/src/lib.rs
core/src/nats.rs
dev/tests/agent.rs
dev/tests/cert.rs
dev/tests/scheduler.rs
drone/src/agent/mod.rs

Currently, NATS subscriptions (both jetstream and not) return a `Result<Option<_>>`, with the semantics:
- `Ok(Some(_))` means that a value was successfully parsed from the stream.
- `Ok(None)` means that the stream was closed without error.
- `Err(_)` means that an error occurred retrieving the value.
This means that the caller has been responsible for handling these errors. In practice, we usually allowed these errors to bubble up and terminate the process, which was only intended as an interim solution.
The ideal behavior is for the code calling the subscriber to be able to have a reliable stream of (error-free) data, but to log an error if a parse error occurs. This PR achieves this by moving the error handling (logging) into the subscribers.

Handle NATS parse errors

---

drone/migrations/20220529222220_initial-db.sql
drone/sqlx-data.json
drone/src/database.rs

We should be synchronizing the `route` table with drone liveness. I'll follow up with a PR that does that, and tests it. For now, this fixes a correctness issue by ensuring that only one route can point to the same local IP at any given time.

Fix route duplication issue

---

controller/src/lib.rs
core/src/lib.rs
core/src/timing.rs
drone/src/agent/docker.rs

This creates a `Timer` struct, and uses it to record timings of a number of things:
- Scheduling a backend
- Pulling an image
- Creating a container
- Starting a container
Ideally I'd like to be able to generate a full flamegraph from scheduler request to backend ready, but this is a start in that direction.

Add timings for certain startup tasks

---

controller/src/scheduler.rs
core/src/messages/agent.rs
dev/tests/scheduler.rs
drone/src/agent/mod.rs

This adds a `ready` field to `DroneStatusMessage` which will be used to support draining (#129).
The field is currently always set to `true`, and is not respected by the scheduler.

Add ready field to DroneStatusMessage to support draining (#129)

---

drone/src/proxy/service.rs

When a backend is running, the backend can set its own CORS headers. However, after a backend is shut down, it defaults back to the strict default CORS settings. This change sets the CORS header for the 404 page to accept all origins.
Security-wise, this doesn't expose anything that wasn't exposed before. The 404 page returned doesn't look at authentication headers or cookies, it simply reveals that a backend no longer exists, which any internet-connected device could already determine.

CORS header for 404

---

.github/workflows/tests.yml
Cargo.lock
controller/src/scheduler.rs
core/src/messages/scheduler.rs
dev/src/timeout.rs
dev/tests/agent.rs
dev/tests/cert.rs
dev/tests/scheduler.rs
drone/src/agent/backend.rs
drone/src/agent/mod.rs

This implements a basic version of drone draining.
- Adds a `DrainDrone` message type. The response of `DrainDrone` is a unit type (`()`), used to acknowledge that the message was received by the drone it was intended for.
- Adds a listener for `DrainDrone` messages to the agent.
- Adds a `watch` channel that the listener can use to send changes to the readiness value to the `ready_loop`.
- Removes drones from the scheduler's view when they indicate that they are not ready.
Additionally, I made some changes in order to test it:
- `timeout` returns a `Result<T>` instead of `T`, and returns an `Err()` instead of panicking.
- `expect_status_message` takes an additional argument which is asserted to be the readiness status of the drone.

Support drone draining (#129)

---

controller/Dockerfile
drone/Dockerfile
drone/run_cached_iff_cache

this change just removes the use of sccache when $PLANE_SCCACHE_BUCKET is not set (its slow to not have this set as sccache makes http requests and waits for them to fail)

Do not use sccache when S3 bucket url not set in $PLANE_SCCACHE_BUCKET (fixes slow docker build times when that variable is unset)

---

controller/Dockerfile
drone/Dockerfile
sample-config/compose/plane.yml

using [] does not work as docker interprets [ as the start of an "exec" form. 
"" as default arg in compose does not work because compose interprets "" literally and passes in "" instead of the null string.

 use test command explicitly instead of [ ] alias in docker run and remove "" as default arg in compose

---

drone/src/proxy/certs.rs

This allows the codebase to be compiled on `stable-aarch64-apple-darwin` (#254)

Use platform-agnostic watcher type

---

.devcontainer/Dockerfile
docs/docs/getting-started.md
drone/src/agent/engines/docker/util.rs
sample-config/compose/plane.yml

- Improve devenvironment
- Add `autoSetupRemote` git configuration
- Add NATS CLI
- Docs nit (remove unnecessary `cd`)
- Quiet logs a bit by removing unnecessary `Unhandled container action` messages
- Quiet warning about `NATS_FLAGS` being unset

Assorted small fixes

---

core/src/nats.rs

This fixes the bug in `list-dns`. Background on the bug:
- Until `async_nats` supports concrete error types, we have to match on the error message string to know when we've reached the end of a stream.
- When this was first implemented, there was a typo in the error string. I simultaneously submitted a PR to `async_nats` to fix the typo.
- My change to `async_nats` landed, but I didn't fix the typo on the Plane side, so the match case fell through.
This PR fixes the typo on the Plane side, and `plane-cli list-dns` now works for me.

Fix list-dns command (#258)

---

cli/src/main.rs
core/src/types.rs

`get_all` works by fetching messages from a NATS consumer until it returns a specific error message. This means in the best case, there are two round-trips to NATS to fetch a list of messages. If a new message is received between the first and second round-trip on a subject that has already been sent, that message will be sent again.
Currently, `get_all` is only used by the cli. This adds deduplication in both locations that `get_all` is used, and also sorts the results.

Deduplicate drones in CLI

---

Cargo.lock
cli/Cargo.toml
controller/Cargo.toml
core/Cargo.toml
core/src/messages/agent.rs
core/src/messages/scheduler.rs
dev/Cargo.toml
dev/src/util.rs
drone/Cargo.toml
drone/src/agent/executor.rs

This will enable #145, but doesn't actually implement the schema change, because that will be a breaking change.
This is the first stage of a two-stage deploy. Once this version of Plane is rolled out to all drones and controllers, we can make the optional `cluster` fields non-optional.

Add cluster to messages (prereq of #145 and #274)

---

core/src/messages/agent.rs
drone/src/agent/engines/docker/mod.rs

Instead of treating all Docker errors as an image not existing, we should propagate non-404 errors.
This also renames `DockerPullPolicies` to `DockerPullPolicy` for consistency.

Propagate errors that occur in image_exists

---

Cargo.lock
cli/src/main.rs
controller/src/scheduler.rs
controller/src/ttl_store/ttl_list.rs
controller/src/ttl_store/ttl_multistore.rs
core/Cargo.toml
core/src/lib.rs
core/src/messages/agent.rs
core/src/messages/dns.rs
core/src/messages/mod.rs
core/src/messages/state.rs
core/src/nats.rs
core/src/types.rs
core/src/views/mod.rs
core/src/views/replica.rs
dev/tests/scheduler.rs
drone/src/agent/backend.rs
drone/src/agent/executor.rs
drone/src/agent/mod.rs
drone/src/proxy/certs.rs

Motivation, design, and broader plan discussed in #278.
This PR introduces a concept of a "view", which is a data structure that is synchronized so that it mirrors the state of the overall system.
`core/src/views/mod.rs` contains three views implemented in this PR, arranged as a three-level tree.
- `SystemView` represents the entire state of a multi-tenant system. 
- `ClusterView` represents the state of a cluster, consisting of a map from drone ID to `DroneView`, and from backend ID to the `DroneId` of the drone it is running on. The latter data structure is used for routing.
- `DroneView` represents the state of an individual drone, including the state of running backends.
The views themselves are not connected with the outside world. The only external mutator is …

State replication refactoring

---

cli/src/main.rs

This allows passing multiple values as `-e FOO1=BAR1 -e FOO2=BAR2`, etc. This was supposed to be the case all along; using `Option` was a bug.

Fix --env so that it accepts multiple values

---

dev/tests/proxy.rs
drone/src/config.rs
drone/src/plan.rs
drone/src/proxy/mod.rs
drone/src/proxy/service.rs

This adds a flag to the proxy to allow a "passthrough" `SocketAddr` used when a backend can't be resolved. _All_ unknown hosts will be proxied to this backend, but it will all be TLS terminated with the same certificate, so if this is used to resolve other hostnames a custom certificate will need to be passed in which covers all of them.
Only HTTP is supported for the upstream connection.
This will close #289.

Add passthrough flag for proxy

---

cli/src/main.rs
core/src/messages/agent.rs
core/src/nats.rs
dev/src/util.rs
dev/tests/agent.rs
drone/src/agent/engines/docker/mod.rs
drone/src/config.rs

For maximum flexibility, I chose to simply pass the json value through. The advantage is that any possible volume configuration can be passed through; the disadvantage is that we don't check the schema until it arrives at the drone, so it's a bit tricker to debug. However, as a first pass, I think this is a step in the right direction.

Provide a way to pass a volume mount (#294)

---

drone/src/agent/engines/docker/mod.rs
drone/src/config.rs

This PR allows a `docker.syslog` config to be passed to Plane. When it is provided, when backends are started, they are started with the `syslog` log driver and passed the value given to `docker.syslog` as the `syslog-address` argument. The `syslog-format` argument is set to `rfc5424`.

Allow syslog to be passed to docker

---

core/src/messages/agent.rs
drone/src/agent/backend.rs
drone/src/agent/engine.rs
drone/src/agent/engines/docker/mod.rs
drone/src/agent/engines/docker/util.rs

This adds a `cluster` field to all messages that cross the drone<>controller boundary.
Logs are an exception. For now, drones will be allowed to publish (but not subscribe) to `logs.drone.>`.
Planning doc: https://docs.google.com/document/d/1hXeucu2e5zuMD2f0Ft3K9wpRaJ8hp0zniFUK8s6HP9w/edit

Add cluster to message schemas

---

Cargo.lock
core/Cargo.toml
dev/Cargo.toml
drone/Cargo.toml

We were using our own fork of bollard until our PR got merged and published. It has now been published.

Update bollard to crate version

---

Cargo.lock
cli/Cargo.toml
controller/Cargo.toml
controller/src/run.rs
core/Cargo.toml
core/src/messages/agent.rs
core/src/messages/cert.rs
core/src/messages/dns.rs
core/src/messages/logging.rs
core/src/messages/scheduler.rs
core/src/nats.rs
drone/Cargo.toml

This is a step in the transition to a new NATS subject schema. Once we switch the controller to listen on the new subjects, the old subjects will be removed.

Send duplicate messages to new and old NATS subjects

---

core/src/messages/agent.rs

When using user/password credentials, Docker makes a round trip to an authentication server to obtain a JWT before pulling the image. The Docker API provides an alternative where we can provide this JWT directly. This PR exposes that option so that the spawner can avoid the round-trip if it already has an identity token.

Add identity token option

---

.github/workflows/build-cli-image.yml
.github/workflows/build-controller-image.yml
.github/workflows/build-drone-image.yml
.github/workflows/build-test-image.yml
.github/workflows/clippy.yml

The github action is just kicking off a depot job anyway, so it doesn't need to be heavyweight.
I also removed it from the clippy one because we shouldn't need 16 cores just to run a linter.

Stop using 16 core workers

---

Cargo.lock
core/Cargo.toml
core/src/messages/agent.rs
core/src/messages/cert.rs
core/src/messages/dns.rs
core/src/messages/logging.rs
core/src/messages/scheduler.rs
core/src/nats.rs
dev/src/util.rs

Now that the latest version of Plane (controllers and drones) listen on the new subjects, we can make those the default and stop sending to the old subjects.

Disable publishing to old subjects

---

core/src/nats_connection.rs
dev/src/resources/nats.rs

In NATS, we need to use user/pass auth if we want multiple sets of credentials. This enables that.

Add username/pass auth in Plane

---

cli/src/main.rs
core/src/messages/agent.rs
dev/src/lib.rs
dev/tests/agent.rs
drone/src/agent/executor.rs

This adds a new backend state called "Lost". Right now, Plane does not directly set a backend's state to Lost. It is, instead, a state that is set by the operator of the Plane cluster mostly for semantic reasons.

add BackendState::Lost

---

drone/src/agent/engines/docker/mod.rs

We should expose this through the API as well but for now this is useful for debugging.

Log backend exit code

---

core/src/messages/agent.rs
dev/tests/agent.rs
drone/src/agent/engines/docker/mod.rs

This updates the `BackendStatsMessage` properties and stats polling interval from 10s -> 5s.

update BackendStats interval & message contents

---

drone/src/agent/mod.rs

If a backend termination request fails to find a backend to terminate, the Result is lost. This just makes sure we warn in the console if that happens.

log backend termination failure

---

.gitignore
README.md
controller/src/drone_state.rs
controller/src/state/mod.rs
controller/src/state/world_state.rs
core/src/messages/agent.rs
core/src/nats.rs
dev-cli.sh
dev-controller.sh
dev-curl.sh
dev-drone.sh
dev-nats.sh
drone/src/agent/engines/docker/mod.rs
drone/src/agent/executor.rs
sample-config/dev-config/README.md
sample-config/dev-config/controller.toml
sample-config/dev-config/drone.toml
sample-config/plane-config/README.md

This PR makes it easier to develop Plane locally.
It:
- Removes some of the more especially chatty logging. This is recently-introduced logging that is not load-bearing.
- Adds `./dev-*.sh` scripts to simplify common tasks.
- Adds Plane config files for running locally, including a `curl` wrapper.

Improve local development ergonomics for Plane

---

cli/src/main.rs
core/src/state/world_state.rs
dev-nats.sh

Also:
- fixes `nats` -> `nats-server` in `dev-nats.sh`
- switches some hashmaps to btreemaps so that order is preserved in CLI.

get list-drones to work

---

core/src/state/world_state.rs

Meta is only populated when drones start, so if we require meta we can't schedule on existing drones.
This temporarily allows drones with no meta to be scheduled to. Once we've rolled drones and populated the state, we can uncomment this.

Temporarily ignore drone with no meta

---

core/src/messages/mod.rs
core/src/nats.rs
core/src/nats_connection.rs

Previously, we created streams lazily the first time they were used. Since we are intentionally reducing the number of streams we use (likely down to 1), it's better just to construct them upfront.
Since there is a cost to creating streams, ideally we would do something fancy like attempt to read/write a stream, and create it only if the stream does not exist. But for now, this removes some cruft.

Simplify jetstream stream creation

---

Cargo.lock
cli/Cargo.toml
cli/src/main.rs
controller/Cargo.toml
controller/src/plan.rs
controller/src/run.rs
core/Cargo.toml
core/src/nats.rs
core/src/supervisor.rs
dev/Cargo.toml
dev/src/resources/nats.rs
drone/Cargo.toml
drone/src/agent/engines/docker/mod.rs

The drone was failing because it would try to create jetstreams on load. This changes the behavior so that only the controller does this. This also means that the CLI (and other users of the `TypedNats` interface, like p2) will not create these streams, which I think is correct: the controller essentially "owns" them.
This PR also includes a version bump, dependencies update, and some other tidying.

Only create jetstreams from controller

---

controller/src/drone_state.rs
controller/src/lib.rs
dev/tests/scheduler.rs

We had been redundantly emitting `Assignment` messages to ensure that backends existing at the time of the transition to the state machine were picked up. Now we don't need to because going forward the scheduler will emit an `Assignment` message for backends it schedules.

Remove assignment from backend message

---

drone/src/agent/executor.rs

So the issue here is that for whatever reason after the terminate signal is received, another interrupt signal arrives as as consequence of the fact that the thing just got stopped. This then tries to terminate it again, which leads to an error.

fix double termination

---

drone/src/agent/executor.rs

when in a terminal state, this closes the receiver for interrupts, this means that we can't have double .stop() calls.

small refactor to not tracing::error when expected error

---

controller/src/lib.rs
core/src/nats.rs

Previously, when we wanted a state snapshot (e.g. for `list-drones`), we would look at the sequence number of the state and read all messages up to that sequence number. This would work if we never deleted messages, but we only keep one message per subject, so it could happen that a message would come in after the snapshot sequence number which would mean that the client would never receive the new OR old value.
This changes the behavior to read until there are no more messages pending, which is the recommended way to do it. In conjunction with the nats-server update, this seems to work well.
I have also switched from logging the entire `SpawnRequest` to only logging the metadata.

Fix behavior of state initialization

---

drone/src/proxy/service.rs

Connections time out. It's just the cycle of life. We don't need to `ERROR` log it.

Ignore connection timeout

---

core/src/state/world_state.rs

This is an edge case that only comes up when the NATS data is dropped, but it's a good catch in case that happens (it does occasionally when I'm mucking with NATS on staging)

Don't schedule if a drone is missing IP information in the controller

---

Cargo.lock
cli/Cargo.toml
core/Cargo.toml
core/nats-macros/Cargo.toml
core/src/nats.rs
dev/Cargo.toml
metrics/Cargo.toml

Updates the async-nats version and uses the new `inactive_threshold` parameter to keep the consumer alive for longer.

Set inactive threshold for NATS consumers

---

cli/src/main.rs
controller/src/lib.rs
core/src/messages/state.rs
core/src/state/world_state.rs
dev/tests/dns.rs
dev/tests/drone_state.rs
dev/tests/scheduler.rs

If a backend has a bearer token and a lock, and we send a spawn request with the same lock, the returned result now includes the bearer token.
This works by attaching the bearer token to the drone assignment message.

Make locks work with bearer tokens

---

Cargo.lock
cli/Cargo.toml
cli/src/main.rs

Any backend not in the `Ready` state and for which we haven't heard from in 24 hours is removed from controller's world state.

Cleanup cleans up abandoned backends

---

drone/src/plan.rs

reasoning here is as follows:
if certs provided, with no https port -> serve https on 443
if certs proved, https_port provided -> serve https on https_port
if certs not provided, https_port provided -> panic
if certs not provided, https_port not provided -> serve http
the change from the previous pr is in case 1. while there is some semantic value in requiring the https_port to be specified, it seems reasonable to infer that a user providing keys will want https, and it won't break existing configs.

remove need to specify https_port

---

core/src/nats.rs

The subject for assignment messages was renamed from `state.cluster.{}.backend.{}` to `state.cluster.{}.backend.{}.assignment` for consistency with `state.cluster.{}.backend.{}.lock`.
This allows both message types to be used for an interim period, so that deploying still captures existing backends on all subjects. After this has been live for long enough for existing drones to be cycled out, we can roll this back.

Temporarily ignore assignment message subject mismatches

---

core/src/nats.rs

The latest clippy finds `PhantomData::default()` redundant.

Satisfy clippy

---

Cargo.lock
README.md
controller/Cargo.toml
controller/src/config.rs
controller/src/http_server.rs
controller/src/lib.rs
controller/src/plan.rs
controller/src/run.rs
dev-nats.sh
sample-config/dev-config/controller.toml

This implements an HTTP API that is a subset of the NATS API. It aims for compatibility with jamsocket.com, so that jamsocket users can test locally with Plane.

Add HTTP API to Plane controller

---

core/src/messages/agent.rs
drone/src/agent/backend.rs
drone/src/agent/engine.rs
drone/src/agent/engines/docker/mod.rs
drone/src/agent/engines/docker/util.rs
drone/src/agent/executor.rs

This adds the drone's ID to backend stats messages which helps consumers - specifically metrics consumers - not have to do extra queries before adding relevant tags to the metrics data.

add drone id to BackendStats messages

---

drone/src/proxy/service.rs

It's common for bots to probe for vulnerabilities with requests like `GET /environments/.env`. Requests like these turn into error messages that quickly drown out real errors. I'm going to drop these kinds of log messages down to warn.

lower severity of log message from error to warn

---

core/src/messages/agent.rs
drone/src/agent/engines/docker/mod.rs

Passes a `PORT` env var to a backend. Does not replace an existing value if one is provided in the spawn request.

Pass PORT environment variable to docker backend

---

core/src/messages/agent.rs

The cpu period was incorrectly being serialized as seconds, instead of microseconds, this corrects that, and also clarifies that the total cpu time ulimit is serialized as seconds

correct serialization of cpu period, and better description

---

cli/src/main.rs

This command doesn't do any validation, simply publishes lost messages for the backendids supplied on the command line. I do not think that this command should access the world state to check that the backend exists because it'll slow down the command.
I considered adding an AbandonRequest style thing with something in the controller, but decided against it since it would be strictly more work for no real benefit.

Add mark-backend-lost command to mark backends as lost [DIS-1294]

---

drone/src/agent/engines/docker/mod.rs

the docker.stats() call fails with stream: false, one_shot: true for docker 24.0.7 (this is because the response for those options now returns an object that does not have the name or id fields set, which bollard considers to be required)
this should be reverted once
https://github.com/fussybeaver/bollard/pull/347 has landed.

turn one_shot off for docker stats

---

docker/docker-compose.yml

Small fix that gets `dev/psql.sh` script working when running postgres with docker compose.

fix dev/psql.sh script when running docker compose

---

.github/workflows/clippy.yml
.github/workflows/formatting.yml
.github/workflows/plane2-build-image.yml
.github/workflows/plane2-clippy.yml
.github/workflows/plane2-rustfmt.yml
.github/workflows/plane2-tests.yml

- Some existing plane workflows are not configured to run on specific branches; this makes them run only on `main`.
- Adds (plane2-preview) to action names to differentiate them

Improve plane2 preview workflows

---

plane2/tests/common/resources/pebble.rs

This doesn't seem to change much, but we should have it anyway.

Disable pebble sleeps in test

---

plane2/src/bin/cli.rs
plane2/src/client/mod.rs
plane2/src/controller/connect.rs
plane2/src/controller/core.rs
plane2/src/controller/mod.rs
plane2/src/database/connect.rs
plane2/src/database/mod.rs
plane2/src/main.rs
plane2/src/types.rs
plane2/tests/common/test_env.rs

- Adds a cli option to controller to pass a controller URL.
- Pipes a `PlaneClient` through to the database so that it can generate a status URL.
I don't love passing a client around so much and think we could refactor that a bit, but this does the trick for now.

Return a status URL from connect request

---

plane2/src/controller/drone.rs
plane2/src/drone/heartbeat.rs
plane2/src/drone/mod.rs
plane2/src/protocol.rs
plane2/src/proxy/proxy_connection.rs
plane2/src/typed_socket/mod.rs
plane2/src/types.rs
plane2/tests/backend_actions.rs

From a `TypedSocket` connection, we have a way to create a `TypedSocketSender` which lets us send messages from elsewhere in the program. The problem is, the `TypedSocketSender` still takes messages of the top-level protocol type, so e.g. the heartbeat sender needs to construct a `MessageToDrone` even though it only wants to send messages of the `MessageToDrone::Heartbeat` variant.
This PR changes `TypedSocketSender` so that it holds a boxed callback for converting an input into the type that needs to be sent on the wire. For example, instead of the old way:
```rust
let sender = conn.sender();
sender.send(MessageFromDrone::Heartbeat(Heartbeat {...}));
```
We now have
```rust
let sender = conn.sender(MessageFromDrone::Heartbeat);
sender.send(Heartbeat {...});
```

TypedSender alteration

---

README.md
dev/cli.sh
plane/src/admin.rs
plane/src/lib.rs
plane/src/main.rs
plane/src/proxy/cert_pair.rs

This moves the cli from a separate binary to the `plane admin` subcommand. The main advantage of this is that it allows us to ship one docker image that can be used both to run controllers/nodes/proxies and also to run admin commands.

Move cli into main plane binary

---

.github/workflows/plane2-build-image.yml

This renames the docker image generated by the build from `plane/plane-preview` to `plane/plane`.

Remove 'preview' from image name

---

README.md
docker/cli.sh
docs/pages/quickstart-guide.mdx

Previously, following the tutorial required an install of rust/cargo and would build the CLI. This uses Docker for that part instead.

use docker for cli commands

---

docs/theme.config.jsx

This is used to generate the “edit this page” links, which are currently broken.

Fix docs repo base

---

plane/schema/derived_schema.sql
plane/schema/migrations/20240105213756_make-controller-ip-nullable.sql

The controller IP is set by `inet_client_addr()`, which can return `NULL` if postgres is connected to via a domain socket.
https://pgpedia.info/i/inet_client_addr.html

Make controller IP nullable

---

plane/src/admin.rs
plane/src/client/controller_address.rs
plane/src/client/mod.rs
plane/src/controller/mod.rs
plane/src/typed_socket/client.rs

Plane can be configured to use a bearer token by sending a connection string like `https://my-bearer-token@my-plane-controller.dev`. Previously, this was implemented in `TypedSocket` and so it only worked for WebSocket connections, not regular HTTP GET/POST requests.
This moves the logic into the client, allowing us to use the same code path for both regular and WebSocket requests.
This also removes base64-encoding from the conversion step. base64-encoding is typically used in `Basic` auth, but not `Bearer` auth.

Allow bearer tokens in client, not just typed socket

---

plane/src/init_tracing.rs

This is useful because it means the #[tracing::instrument] decoration on some thing immediately shows up in logs.
Otherwise it only shows up alongside a tracing event (info!, debug! etc)

adds tracing spans to tracing_subscriber capture

---

plane/src/controller/drone.rs
plane/src/protocol.rs

The fields used here are selected based on their utility to clients
for monitoring (basically, mem_total and cpu_used) and to the controller
for scheduling (the other fields, since the scheduler really cares about
available memory, not just allocated memory)

Add backend metrics message

---

plane/src/drone/docker/mod.rs
plane/src/typed_socket/mod.rs
plane/src/util.rs

This is just to be able to stick tracing::instrument in places, it's especially useful to be able to do this on TypedSocketSender::send

Some debug derivations and implementations

---

plane/src/names.rs

When deployed on EC2, drones and proxies have two unique identifiers: the plane-side identifier and the EC2 instance ID. Rather than creating a random ID for plane and then having to look up the association between plane-side ID and EC2 instance ID, it is preferable to derive one from the other.
We have no control over the EC2 instance ID, so the only way to associate the two is to generate the Plane-side node ID from the instance ID.
The instance ID generated by EC2 is 19 characters long. The prefix Plane applies is two characters long. If we want to add information about the cluster and environment (stg/prod/etc.) to the name, we need another three hyphens. That leaves only 6 characters remaining for both the name of the cluster and environment. This PR gives us a bit more breathing …

Bump name length

---

docs/pages/deploy-to-prod.mdx
plane/plane-tests/tests/common/test_env.rs
plane/src/admin.rs
plane/src/dns/mod.rs
plane/src/dns/name_to_cluster.rs
plane/src/main.rs

This supports an optional DNS zone that can be provided to the DNS server. If a zone is provided, it will be stripped off of an incoming request before it is processed.
For example, if the server is started with `--zone example.com`, a request for `TXT` records on `_acme-challenge.foo.bar.baz.example.com` would be treated as a request for TXT records of the cluster `foo.bar.baz`.
If a zone is provided, requests that are not under that zone will fail.
This is useful because it allows us to use CNAME delegation for `_acme-challenge` subdomains.
For every cluster, the `_acme-challenge.[cluster name]` domain should have a CNAME record of `[cluster name].my.dns.server`. The A record for each of these records should point to the IP of the DNS server. The DNS server would be configured with …

Support suffix for DNS server

---

plane/src/admin.rs
plane/src/client/mod.rs
plane/src/typed_socket/client.rs
plane/src/typed_socket/mod.rs

Fixes clippy lints, mostly by extending the `PlaneClientError` type and using it instead of `unwraps` in the admin tool.

Fix clippy lints

---

plane/src/proxy/cert_manager.rs

Currently, we obtain the certificate for wildcard domains only, which was ok before because we required subdomain routing. Now that we also allow path-only routing, we also want the cert to apply to the base domain itself.

Add non-wildcard domain to certificate request

---

plane/.sqlx/query-bb4d67150e3808a0b443ad0e1fd66b3b5f713518a772007b6caa85a86d12acf6.json
plane/plane-tests/tests/backend_status_in_response.rs
plane/src/database/backend_key.rs
plane/src/database/connect.rs
plane/src/types.rs

- Adds a field `status` to a `ConnectResponse`:
- When a backend is newly spawned, it takes on the value `BackendStatus::Scheduled`
- When a backend already exists, it takes on the last status from the database

Return status with connect response

---

docker/Dockerfile
docker/quickstart/Dockerfile
plane/src/main.rs

- Adds a command `version` which prints the current version and git hash
- Adds the `.git` directory to the context for docker builds so that the build is aware of the current git hash

Fix hash version and add version command

---

plane/plane-tests/tests/controller_status.rs
plane/src/database/controller.rs

We have been emitting a "heartbeat" message, which gets stored in the `event` table. But it's only used for tests, and adds a bunch of machinery. This removes it for a simpler (though admittedly uglier) sleep in the tests.

Make controller heartbeats ephemeral

---

docs/pages/developing.mdx

[`nextest`](https://crates.io/crates/nextest) appears to be a real (but empty) crate. Replaced with the intended `cargo-nextest`.

[docs] Fix typo in cargo nextest install instructions

---

docs/pages/developing.mdx

Without "Allow the default Docker socket to be used" (not on by default), drone was having trouble connecting to docker on Mac OS:
```
$ ./dev/drone.sh 
[...]
ERROR plane::drone::docker: Error receiving Docker event. e=HyperResponseError { err: hyper::Error(Connect, Os { code: 2, kind: NotFound, message: "No such file or directory" }) }
```

Document Mac docker setting prereq for local dev

---

plane/src/controller/connect.rs
plane/src/controller/drone.rs
plane/src/controller/error.rs
plane/src/controller/proxy.rs
plane/src/database/connect.rs

Adds an error kind type.
There's probably some refactoring to do here, e.g. the `StatusCode` could be determined by adding a `status()` method to the `ApiErrorKind` itself. But I wanted to focus on getting the change to the message interface in for now; that way we can refactor the code later without worrying about breaking the interface.

Add error kind

---

docs/pages/quickstart-guide.mdx
plane/src/admin.rs

Currently, CLI commands `connect` and `terminate` require you to specify `--wait` if you want them to wait. This should be the default, and `--immediate` should be provided for the current default behavior.
Fixes #589
Merge prerequisites
===================
Test Plan
=========
Tested for expected behavior change in the CLI.
Setup:
------
In different terminals, run:
```bash
$ ./dev/postgres.sh && ./dev/controller.sh
```
```bash
$ ./dev/drone.sh
```
```bash
$ ./dev/proxy.sh
```
Previous behavior
-----------------
Default behavior of `connect`:
```bash
$ ./dev/cli.sh connect --cluster 'localhost:9090' --key 'my-first-backend' --image 'ghcr.io/drifting-in-space/demo-image-drop-four'
Created backend: xg8rilbuvssw0o
URL: http://localhost:9090/A8mxZ49t_H47v44w25h-Sy-5lLfScnEqlnGCwAcLick/
Status …
```

Make `--wait` the default for `connect` and `terminate`

---

docker/quickstart/supervisord.conf
plane/src/types/backend_state.rs

I'm seeing some `Terminating { last_status: Terminating, .. }` BackendStates. I think this is only possible if calling `to_terminating()` on an already-terminating status. This alters the `to_terminating()` and `to_terminated()` methods to return `self.clone()` if the state is already terminating or terminated since these methods should return states where the `last_status` is the last _alive_ status.
Also pushed a commit that fixes an issue with the Quickstart image on Linux where the drone can't reach the session backend containers. Maybe there's a more elegant solution, though? More info here: https://stackoverflow.com/questions/48546124/what-is-the-linux-equivalent-of-host-docker-internal

address issue when calling to_terminating() on an already-terminating state

---

plane/plane-tests/tests/common/test_env.rs
plane/plane-tests/tests/metrics.rs
plane/src/drone/docker/commands.rs
plane/src/drone/docker/mod.rs
plane/src/drone/mod.rs
plane/src/init_tracing.rs
plane/src/main.rs

- Adds a CLI flag for passing log config as JSON (`--log-config`)
- Passes the log config to Docker
- Some refactoring to pass `PlaneDocker` around instead of `Docker` plus `docker_runtime`, which allows us to pass the log config and makes some function signatures shorter.

Add log config passthrough

---

plane/.sqlx/query-7d4c92420e542e7086f81e00e16087bf8c2b29a618d7eab3cc7956a9ee456573.json
plane/.sqlx/query-ca6e40ee9cea913e0d6691eb375de7b7e4afe57f64fb00ae6d6bab3a6d2a6634.json
plane/plane-tests/tests/common/test_env.rs
plane/src/bin/db-cli.rs
plane/src/cleanup.rs
plane/src/controller/mod.rs
plane/src/database/backend.rs
plane/src/database/connect.rs
plane/src/database/mod.rs
plane/src/lib.rs
plane/src/main.rs

This adds a loop to the controller that runs ever 15 minutes and cleans up:
- old backends (only if configured with a maximum age)
- expired tokens
It also adds a dbcli command for doing this cleanup manually.

Add plane cleanup loop

---

plane/src/drone/backend_manager.rs
plane/src/drone/docker/commands.rs
plane/src/drone/docker/mod.rs
plane/src/types/mod.rs

Clippy doesn't like long argument lists, we silence its warnings though a combination of shortening an argument list and telling clippy to be quiet where we don't (yet) want to.

Pacify clippy

---

plane/.sqlx/query-d0a47530eee694a2c3622050e484ad9f8a26f490cbc3924d2fad27b3f83bcfed.json
plane/src/database/backend.rs

When drones are overloaded, they may not be able to start a backend, so it gets stuck in a scheduled state. The controller sends termination requests to the drone to terminate the scheduled backend, the messages are acked, but the scheduled backends don't get set to "terminated". This changes the controller to only try sweeping backends that are non-scheduled and non-terminated.

only consider non-terminated and non-scheduled backends as termination candidates

---

plane/.sqlx/query-6ffe4dfc2048ec110ea36bbb22cb0e48971f2d2a8b25e3e82b64e4c0fae6aff7.json
plane/src/database/node.rs

I'm adding a function here to the PlaneDatabase that will let us pull a Node from the DB by ID. This will be used in the platform-monitor (and by other clients) to pull more information about a Node when we receive `NodeConnectionStatusChange` messages. It uses the same marshaling logic as the `list()` function.

add get_by_id() fn to the node database

---

plane/src/drone/key_manager.rs
plane/src/drone/mod.rs

It seems that occasionally the spawn request from the controller to the drone is received twice. We should probably add some deduping logic elsewhere, but a good sanity check when spawning is to fail with an error if the backend already exists.
This implementation piggybacks on the fact that the first thing we do with a spawn request is add the backend to the key manager. We already have a lock on the key manager when we do this, so it's cheap to additionally check if the backend ID is already in there.

Ignore spawns with duplicate key

---

plane/src/proxy/cert_manager.rs

If a proxy fails to get a cert, it currently waits for 1 minute. This generally means that if a proxy is in a fail loop, it may keep acquiring the lock, preventing other proxies from getting a cert.

Increase timeout after failure to obtain lock

---

plane/plane-tests/tests/common/test_env.rs
plane/src/drone/docker/mod.rs
plane/src/drone/executor.rs
plane/src/drone/mod.rs
plane/src/main.rs
plane/src/util.rs

- Add a `prune` function to `PlaneDocker` that:
- Removes docker containers labeled as Plane backends over a certain age (based on creation time)
- Optionally removes images that are not associated with a container
- Refactor some of the drone configuration that is passed as a growing list of arguments into a `DroneConfig` struct
- Adds cli flags `--auto-prune` and `--cleanup-min-age-seconds` to control pruning behavior.
This also removes the behavior where the drone would attempt to obtain its IP from Docker DNS. Instead, the argument to `--ip` may now be a hostname and will be attempt to be resolved, so you can pass `--ip=host.docker.internal` to achieve the old behavior.
The cleanup loop runs every minute (not currently configurable).
This will close #300.

Clean up containers and images

---

plane/src/dns/mod.rs

Previously, we would only send a TXT record request to the server if one was not already in flight. The problem is if the txt record in flight failed, we would not capture it. This sends txt requests to the server for every request, to avoid that problem.
A better solution is to (briefly) cache these in the DNS server itself, but this should fix the issue for now.

Fix DNS serving

---

plane/src/types/backend_state.rs

Adding a `TerminationReason::Lost` ahead of #650 so we can bring the updated type into Jamsocket before the rest of #650 lands.

add TerminationReason::Lost

---

plane/src/bin/db-cli.rs

This adds a command to the db-cli to mark backends as Lost in cases where a failure mode has left the controller believing a backend is running when it no longer is. We will ideally address these failure modes with bugfixes and reconciliation loops, but while we do that, this will be a necessary tool for making sure the controller's state is correct.

mark-backend-lost db cli command

---

plane/plane-tests/tests/backend_lifecycle.rs
plane/plane-tests/tests/backend_status_in_response.rs
plane/plane-tests/tests/common/test_env.rs
plane/plane-tests/tests/docker_command.rs
plane/plane-tests/tests/drone_pools.rs
plane/plane-tests/tests/metrics.rs
plane/plane-tests/tests/reuse_key.rs
plane/plane-tests/tests/volume_mounts.rs
plane/src/admin.rs
plane/src/drone/docker/commands.rs
plane/src/drone/docker/mod.rs
plane/src/main.rs
plane/src/types/mod.rs

Fixes #586
Design doc here: https://docs.google.com/document/d/1KHkHQ823vzVDBwg5iyF6CW-pMjqNO_3LhmF1v_iNK_0/edit
Notes:
* Drone has an optional `--mount_base` command line arg. This must be an absolute path.
* Spawn requests have an optional `mount` field in the executable config. This can be a boolean or a string (details in the doc). If it's a string, it must be a _relative path_.
* The admin CLI allows you to create a connect request only an optional string `mount` (boolean is not supported).
Tested the API and CLI using the demo detailed below. 
Did extensive unit testing to test all possible types of `mount_base` and `mount` to ensure the correct docker mounting config is generated (in the binds field).
Specifying a relative path for `mount_base` or an absolute path for `mount` will …

Support docker volume mounts

---

Cargo.lock
plane/Cargo.toml
plane/plane-dynamic/Cargo.toml
plane/plane-tests/Cargo.toml
plane/plane-tests/tests/cert_manager.rs
plane/plane-tests/tests/common/test_env.rs
plane/plane-tests/tests/metrics.rs
plane/src/controller/command.rs
plane/src/controller/mod.rs
plane/src/dns/command.rs
plane/src/dns/mod.rs
plane/src/drone/command.rs
plane/src/drone/docker/commands.rs
plane/src/drone/docker/mod.rs
plane/src/drone/mod.rs
plane/src/lib.rs
plane/src/main.rs
plane/src/proxy/cert_manager.rs
plane/src/proxy/command.rs
plane/src/proxy/mod.rs
plane/src/serialization.rs

Currently, the pipeline from CLI options to a running Plane drone/proxy/controller/DNS server is a bit ad-hoc and different for each component. This PR standardizes all four into a common pattern:
- The CLI options definition (clap parser) is moved out of `main.rs` and into `[component]/command.rs`. The options structs are given a name ending in `Opts`, e.g. `ProxyOpts`.
- For each component type, an additional `*Config` struct is defined, like `ProxyConfig`.
- Each `*Opts` struct gets an `.into_config()` method which converts it into the corresponding `*Config` type.
The resulting `main` command looks like this:
```rust
async fn run(opts: Opts) -> Result<()> {
match opts.command {
Command::Controller(opts) => run_controller(opts.into_config()?).await?,
Command::Drone(opts) => …
```

Refactor commands

---

docker/quickstart/README.md
docker/quickstart/supervisord.conf

This fixes the Quickstart image on a mac, but breaks it on Linux.
[This PR](https://github.com/drifting-in-space/plane/pull/607) fixed that by relying on the admittedly awkward behavior of the previous `--ip` flag which [was only used](https://github.com/drifting-in-space/plane/pull/642/files#diff-a2f5b466f90757cf3ddcd106024fc1492f9ad5966124478fcb335c6364fb9a5cL200-L206) if `host.docker.internal` didn't resolve to anything.
@paulgb Any ideas on a good way to get this passing in the right IP/host for both Mac and Linux?

fix quickstart image on mac

---

plane/plane-tests/tests/cert_manager.rs
plane/src/proxy/cert_manager.rs
plane/src/proxy/command.rs
plane/src/proxy/mod.rs

`AcmeEabConfiguration` is part of the config schema now, but it stores the EAB key internally as a `Vec<u8>` rather than as a base64-encoded string. This makes for an ugly serialized representation. This changes the internal type to be a base64-encoded string, and parses it into bytes with a method.

Deserialize key as base64

---

plane/plane-tests/tests/cert_manager.rs
plane/src/proxy/cert_manager.rs
plane/src/proxy/mod.rs

This avoids excess ACME account creation by first registering an account on startup, and reusing it for the life of the drone. It does not persist the account across a drone restart (yet) -- this would get a bit messy until we switch over to 100% rustls, after which I am in favor of it.

Reuse ACME account across certs

---

plane/src/controller/drone.rs
plane/src/drone/executor.rs
plane/src/drone/mod.rs

When the postgres connection pool reconnects, it's possible for events to be lost. This periodically checks for unacked messages and sends them to drones.

Handle missed backend actions

---

plane/src/admin.rs
plane/src/client/mod.rs

This fixes two issues:
- The method name should not have `_url`
- The `Authorization` header should be sent

Cluster state API fixes

---

plane/src/drone/backend_manager.rs
plane/src/drone/wait_backend.rs
plane/src/types/backend_state.rs

Backend waits for server to start on 8080. Drone agent checks whether that container has a server running on 8080, but there's no timeout on that. Added a reasonable timeout (5min). If it trips that timeout, hard terminate the backend. Added a termination reason `TerminationReason::StartupTimeout`.

Add a failure to become ready timeout

---

plane/src/proxy/rewriter.rs

Browsers are allowed to provide a comma-separated list in the `Connection` header, but we currently match on the exact string "upgrade", so this breaks. This change switches so that we check if _any_ of the values provided in the connection header match `upgrade`.
Closes #690

Fix WebSocket connection upgrade issue on Firefox

---

plane/src/drone/docker/mod.rs
plane/src/heartbeat_consts.rs
plane/src/types/backend_state.rs

This does two things:
1. Allows a soft terminating state to transition to a hard terminating state
2. Has the `stop_container` command only kill the backend after 30 seconds

allow soft terminating states to be followed by hard terminating states

---

.github/workflows/build-image.yml
.github/workflows/build-quickstart-image.yml
.github/workflows/clippy.yml
.github/workflows/rustfmt.yml
.github/workflows/tests.yml

Some of the actions we use rely on deprecated versions of Node.js; this gets some of the easy ones out of the way.

GitHub action version updates

---

plane/src/lib.rs
plane/src/proxy/proxy_service.rs

- If we return an internal error, log it.
- On requests that Plane handles internally (non-proxied requests), return a server header that includes the version number.

Log unhandled errors

---

plane/.sqlx/query-40cab83a74ad43beb3c150f6f14496cfe9fbe4a7a2253bc38da68cc31007d318.json
plane/.sqlx/query-f88fe0f0f1812332e135e2c543a9dbd0817d260d60ffadc9ccb967869e222840.json
plane/src/admin.rs
plane/src/database/backend.rs
plane/src/protocol.rs
plane/src/proxy/proxy_connection.rs
plane/src/proxy/proxy_service.rs
plane/src/proxy/route_map.rs

- `route_info_for_token` returns `None` if the backend is not ready
- adds `MessageToProxy::BackendRemoved` variant. This will be used for the controller to notify drones when a backend has been terminated, and tells it to invalidate any connection tokens associated with that backend. This is not currently sent from the controller yet, but will be in a future PR.
- Modifies handling of `InvalidConnectionToken` to return `GONE` instead of `FORBIDDEN`.
Fixes DIS-1891

Return GONE on terminated backend

---

plane/src/controller/proxy.rs

This sends notifications to proxies when a backend is terminated (counterpart to #697, which implements the message on the proxy side)

Send remove backend message when backend is terminated

---

plane/src/proxy/rewriter.rs

Stripping all ports breaks the default cluster for localhost testing, `localhost:9090`.
We are already a bit magic with regards to http/https. We assume that if a cluster name has a colon, it's HTTP and runs on that port, and if a cluster name does not have a colon, it is HTTPS and runs on 443. In other words, in production, there's no way for URLs generated and sent to clients to have a port other than the standard HTTPS port 443.
(The https server can run on another port locally, as long as the ultimate client connecting to it is connecting to port 443.)

Only strip port if it's 443

---

plane/src/proxy/rewriter.rs

This adds the header `x-verified-backend` header to requests that get sent to a backend.
This is in support of #712. With the Docker executor, we use the operating system's port mappings to dispatch a request to the right process. With alternate executors, the executor itself may want to provide the HTTP server and dispatch to the appropriate backend. This header gives them that option.

Add backend ID to forwarded request headers.

---

plane/src/proxy/mod.rs
plane/src/proxy/rewriter.rs
plane/src/proxy/subdomain.rs

This moves hostname parsing into its own file and adds unit tests. #702 added some complexity to hostname parsing, so it's worth breaking out and testing that it behaves how we want.

Add unit tests for hostname parsing

---

plane/plane-tests/tests/common/test_env.rs
plane/src/drone/command.rs
plane/src/drone/mod.rs

In service of #712, this makes the type of executor configurable in Plane. Since the executor itself isn't generic yet, docker is the only supported type.
This is a change to the configuration schema, in a way that is backwards-compatible for now. Eventually, the `docker_config` config field (which this change deprecates) will be removed.

Turn executor config into an enum

---

plane/plane-tests/tests/common/test_env.rs
plane/src/drone/command.rs
plane/src/drone/docker/mod.rs
plane/src/drone/executor.rs
plane/src/drone/mod.rs
plane/src/serialization.rs

`PlaneDocker` exposes a method `prune` which is run on a cleanup loop. The specifics of this cleanup are an implementation detail that only the Docker executor cares about. Since we want to move towards `PlaneDocker` implementing a generic, executor-agnostic trait, we want to eliminate this.
The approach here is to move the pruning loop into the PlaneExecutor itself. The loop starts when the executor is constructed, and runs until it is dropped.
In order to facilitate this, the configuration for pruning has to be moved into the executor config instead of the general drone config, which this PR also does.
Part of #712

Move `prune` into PlaneDocker executor

---

plane/plane-tests/tests/common/test_env.rs
plane/plane-tests/tests/metrics.rs
plane/src/drone/backend_manager.rs
plane/src/drone/command.rs
plane/src/drone/docker/commands.rs
plane/src/drone/docker/mod.rs
plane/src/drone/executor.rs
plane/src/drone/mod.rs

I want to create some clarity around terminology in Plane as we move towards generic runtimes (#712):
- **Executor** refers to the generic piece that manages the backend lifecycle
- **Runtime** refers to the code that actually manages the backends
So for Docker, `DockerRuntime` will implement the (as-yet-unimplemented) `Runtime` trait, an instance of which will be owned and managed by the `Executor`.
This moves towards using that terminology. I created it as a standalone PR because it would add a bunch of noise if I did it alongside other changes. All this PR does is:
- Replace `PlaneDocker` with `DockerRuntime`
- Replace `PlaneDockerConfig` with `DockerRuntimeConfig`
- Update a couple of comments

Rename PlaneDocker to DockerRuntime

---

plane/plane-tests/tests/metrics.rs
plane/src/drone/backend_manager.rs
plane/src/drone/docker/commands.rs
plane/src/drone/docker/mod.rs
plane/src/drone/executor.rs

`ContainerId` is an implementation detail specific to Docker, but we pass it across the runtime interface a lot. This changes it so that we only ever pass `BackendName`s around, and derive the container ID from these names where necessary.
Part of #712

Remove ContainerId from runtime interface

---

Cargo.lock
plane/Cargo.toml
plane/plane-tests/tests/metrics.rs
plane/src/drone/backend_manager.rs
plane/src/drone/docker/metrics.rs
plane/src/drone/docker/mod.rs
plane/src/drone/docker/types.rs
plane/src/drone/executor.rs
plane/src/drone/mod.rs
plane/src/drone/runtime.rs
plane/src/drone/state_store.rs

This refactors metrics collection so that it lives entirely on the side of the runtime. This way, docker-specific things are confined to the Docker runtime.
The way it works is:
- `metrics()` on the `Runtime` trait is replaced with a `metrics_callback()` method, which can be used to pass in a callback that is called when metrics are available
- Container "start" events are added to the list of the events that the Docker runtime listens for (nb. these are currently only received if the events stream is being polled -- decoupling this is added as a todo)
- When a container start event is received, we pull the backend ID from the container metadata and start a tokio task which open a metrics stream for that container. When metrics are received, we convert them to a metrics message and invoke …

Refactor metrics out of the executor

---

plane/plane-tests/tests/backend_actions.rs
plane/plane-tests/tests/backend_lifecycle.rs
plane/plane-tests/tests/backend_status_in_response.rs
plane/plane-tests/tests/drone_pools.rs
plane/plane-tests/tests/reuse_key.rs
plane/plane-tests/tests/subdomains.rs
plane/plane-tests/tests/volume_mounts.rs
plane/src/admin.rs
plane/src/client/mod.rs
plane/src/controller/connect.rs
plane/src/controller/core.rs
plane/src/database/backend.rs
plane/src/database/connect.rs
plane/src/database/mod.rs
plane/src/drone/backend_manager.rs
plane/src/drone/docker/mod.rs
plane/src/drone/executor.rs
plane/src/drone/key_manager.rs
plane/src/drone/mod.rs
plane/src/drone/runtime.rs
plane/src/protocol.rs
plane/src/types/mod.rs

- Removes generic parameter from JSON types (like `ConnectRequest`), instead using `serde_json::Value`
- Makes `BackendManager` generic over `Runtime`
Towards #712

Make executor generic over runtime

---

.github/workflows/tests.yml

v3 is deprecated (https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)

Update artifact action to v4

---

plane/src/proxy/rewriter.rs

Requests to `$CLUSTER/$CONNECTION_TOKEN` fail because they don't have a trailing slash. This PR fixes that by proxying to `/` anyway. (When using a static token, we don't strip the token from the path before proxying. In those cases, this proxies to `/$CONNECTION_TOKEN` (no trailing slash).
This is important because some servers (e.g. Nextjs) will redirect to remove a trailing slash. When this happens, the connection through proxy fails, returning a `400 Bad Request`.

allow requests to proxy to not have a trailing slash

---

plane/src/proxy/proxy_service.rs

If the response already has CORS headers set, we shouldn't overwrite them. This also tidies up how we do CORS header setting, by moving the headers into a const.

Don't overwrite CORS headers

---

plane/plane-tests/tests/backend_lifecycle.rs
plane/plane-tests/tests/backend_status_in_response.rs
plane/plane-tests/tests/drone_pools.rs
plane/plane-tests/tests/reuse_key.rs
plane/plane-tests/tests/subdomains.rs
plane/plane-tests/tests/volume_mounts.rs
plane/src/drone/runtime/docker/commands.rs
plane/src/types/mod.rs

This adds a way to pass a network name in a spawn config. This is mostly useful for development.

Add docker network support to spawn config

---

plane/.sqlx/query-1c13ca4f48aba7ddebb5440620eb0813aff74fa98bd1bdede3bf275374e07ffb.json
plane/src/cleanup.rs
plane/src/database/mod.rs
plane/src/database/subscribe.rs

This keeps the event table from growing unbounded if `min_age_days` is set on the controller.

Clean up events

---

plane/src/drone/executor.rs
plane/src/drone/mod.rs
plane/src/drone/state_store.rs

Fixes the following bug:
* drone process restarts
* drone executor's `apply_action` receives a `BackendAction::Terminate` for a backend that's been running since before the restart
* the `self.backends` map does not contain the backend's manager anymore because the process was restarted
* the drone assumes the backend has been terminated and the backend continues running
Tested locally: running `docker ps` shows that all previously created backends are terminated upon drone agent restart.
Creating a unit test for this might involve a side quest because terminate currently hangs when the backend can't be found. This is a pre-existing issue outside of the scope of this bug, and I think the code here is sufficiently straightforward to merge without a dedicated test.
In separate terminals: …

Kill all non-Terminated backends on drone start

---

plane/src/drone/backend_manager.rs
plane/src/drone/executor.rs
plane/src/drone/runtime/docker/mod.rs
plane/src/drone/runtime/mod.rs

In the weird case where the Plane controller asks a drone to terminate a backend that has already been removed from Docker, we currently do nothing but don't do anything to tell the controller to mark the backend as lost. This changes the behavior to do that, via the state store.

Mark backend as terminated when lost

---

Cargo.lock
plane/Cargo.toml
plane/src/typed_unix_socket/client.rs
plane/src/typed_unix_socket/mod.rs
plane/src/typed_unix_socket/server.rs

This is a further refactoring of #743:
- removes dependency on `tokio-util`
- avoids unnecessary `tokio::spawn`s (which can make it hard to reason about behavior) and uses `GuardHandle` to ensure that send/recv loops are terminated when a client/server is dropped
- replaces shutdown handlers with `Drop` impl

Refactor of 743

---

plane/src/drone/mod.rs

This can happen if the message sent by the server was not acknowledged by the drone. It's not actionable, but should be unusual and may be a hint if other things are broken, so demote it to a warning.

Warn on key registered, not error

---

plane/src/drone/mod.rs
plane/src/protocol.rs

This implements `valuable::Valuable` for `BackendAction`, which allows us to log it with structured logging instead of using the debug logger. The executable config is omitted since it may contain sensitive data (although we may consider adding a separate "secrets" config that would be passed alongside the executable config in a future version.)

Implement Valuable for BackendAction

---

plane/src/types/backend_state.rs

The backend status lifecycle has a strict ordering. Backends can move forward in the lifecycle, but not backwards.
On the Rust side, `BackendStatus` is `PartialOrd`, so we can do natural comparisons between backend statuses as they relate to this order. However, on the database side, they are just strings.
We would like to add constraints at the database level, such as "a backend status can never go backwards". In the database, statuses are represented as strings. We could re-implement the comparison logic in the database as a function over strings, but I don't love having the logic live in both Rust and the database.
The alternative implemented here is to create a function from `BackendStatus` -> `i32` which produces a number that reflects the natural order of statuses.
No Plane behavior …

Create a BackendStatus -> numeric mapping

---

plane/.sqlx/query-051c7989e10af66145582f52eeddaebef2b8b92dee44f74c35545491f98ea1f5.json
plane/src/database/drone.rs

Updates the `get_drones_for_pool()` to take a duration instead of only returning drones from the last 45 seconds. This flexibility is useful when wanting to see all the drones that ran over a longer period of time.

query for drones from drone pool with a duration

---

plane/src/proxy/proxy_service.rs
plane/src/proxy/route_map.rs

We have occasionally seen a panic in the proxy where the receiver falls behind. This fixes that by replacing the broadcast channel with a watch channel, since we don't need to keep multiple values around anyway.

Fix proxy panic

---

plane/.sqlx/query-822ae07d4783158bc1912bb623e5107cc9002d519e1143a9c200ed6ee18b6d0f.json
plane/src/controller/mod.rs
plane/src/database/mod.rs

Tested locally:
```bash
$ ./dev/postgres.sh && ./dev/controller.sh
$ curl http://localhost:8080/ctrl/status
{"status":"ok","version":"0.4.12","hash":"c4c10be0"}
$ docker stop postgres
$ curl http://localhost:8080/ctrl/status
{"id":"k1deo8tjiowthy","kind":"Other","message":"Database health check failed"}
```
Note: The status endpoint actually hangs until the default 30 second timeout before outputting this response. This is ok because kubernetes enforces an automatic 1 second timeout on health checks before assuming they're failing.

Check DB in healthcheck

---

plane/src/drone/backend_manager.rs
plane/src/drone/executor.rs
plane/src/drone/key_manager.rs
plane/src/drone/mod.rs
plane/src/drone/runtime/docker/mod.rs
plane/src/drone/runtime/mod.rs
plane/src/drone/runtime/unix_socket/mod.rs

Basically, removes generics everywhere we use them in favor of boxing.
One of the changes here is to do the parsing of executor / backend configs inside the implementation instead of outside. This is necessary if we want to actually use runtimes dynamically, since we won't always know the type we want to parse.
I haven't tested that this works, but it compiles.

Remove generics

---

plane/src/drone/backend_manager.rs
plane/src/drone/state_store.rs
plane/src/types/backend_state.rs

It doesn't make sense to have a ready backend without an address. This avoids that situation by passing the address through `to_ready`.
`BackendState` is sent across the network, so changes to it need to be version-safe. This change is version-safe:
- If a **writer** is on this version and a **reader** is on a prior version, nothing bad can happen. The reader continues to accept `null` a the value, but the writer will never produce that value.
- If a **reader** is on this version and a **writer** is on a prior version, there is technically a code path that produces a `null` here, but:
- It's an error code path, and it logs a warning message
- I could not find any instances of this in our logs

Make ready address required

---

plane/.sqlx/query-40f7fcd5f76e4af0d795a0174322388656ca9868c614462380066d457b4b0b15.json
plane/src/client/sse.rs
plane/src/controller/proxy.rs
plane/src/database/backend.rs

Follows design doc here: https://docs.google.com/document/d/1KpZMyz8E4a7pk_OaIqQKLWWKiLo4SdRhe1MkUy6EyLE/edit
The general approach:
- Introduces [`PartialRouteInfo`](https://github.com/jamsocket/plane/pull/772/files#diff-0abc0d77e47c302d2447792802d4fb6300e2ee6ba14b99cb00016febdc5109e3R639-R660), which is a `RouteInfo` without an address. The address is not known until the scheduled drone sets it when the backend is in the `Starting` state, but everything else in the `RouteInfo` is _always_ available on a valid (non-expired) connection token. A `PartialRouteInfo` [can be upgraded](https://github.com/jamsocket/plane/pull/772/files#diff-0abc0d77e47c302d2447792802d4fb6300e2ee6ba14b99cb00016febdc5109e3R649-R659) to a regular `RouteInfo` once the address is known.
- Introduces …

Proxy waits on (scheduled/loading/starting) backend to become ready

---

plane/src/typed_unix_socket/mod.rs
plane/src/typed_unix_socket/server.rs

We want `server` to be copy safe: we do this successfully by wrapping the `_loop_task` in an `Arc` `GuardHandle`. However, `server`'s `Drop` will attempt to delete the `socket_path` file on every dropped copy -- which isn't the behavior we want. We only want that file deleted when the last copy is dropped. We achieve this similar to `_loop_task`: by creating a new `SocketPath` type (with its own `Drop` impl) and wrapping this type in an `Arc`.

Introduce SocketPath type with copy-safe drop

---

plane/plane-tests/tests/metrics.rs
plane/src/drone/backend_manager.rs
plane/src/drone/command.rs
plane/src/drone/executor.rs
plane/src/drone/key_manager.rs
plane/src/drone/mod.rs
plane/src/drone/runtime/docker/mod.rs
plane/src/drone/runtime/mod.rs
plane/src/drone/runtime/unix_socket/mod.rs

Example usage:
```bash
$ ./dev/drone.sh --executor-socket "/tmp/tmp.sock"
```
This includes work from @paulgb to remove generics (#774) in favor of `Box<dyn ...>>` to enable dynamic dispatch.

Allow drone to run as unix domain socket executor

---

plane/plane-tests/tests/common/test_env.rs
plane/src/bin/db-cli.rs
plane/src/cleanup.rs
plane/src/controller/command.rs
plane/src/controller/mod.rs
plane/src/database/backend.rs

- Adds batching (default size 100).
- Sets the interval to once every 3 minutes (per controller) instead of once every 15 minutes
- Cleans up `backend_key` table too (as long as the keys are expired. This should always be the case, but we fail-safe by not deleting a non-expired key.)

Add batching to cleanup loop and clean up backend_key also

---

.github/workflows/clippy.yml

Caches so we don't download the same deps every PR just to run clippy check.

Cache clippy check

---

plane/plane-tests/tests/docker_command.rs
plane/src/drone/runtime/docker/commands.rs
plane/src/drone/runtime/docker/mod.rs

Two things:
1. Allow me to access `docker` under the hood of the `DockerRuntime` to do custom stuff in a separate runtime. I still want to keep `DockerRuntime` around because some functionality is identical and it allows me to lean on the existing runtime's implementation of stuff.
2. Allow me to re-use the container config, which is by and large identical in a separate runtime -- except for the `backend_name`. Turns out it's not that hard to make that optional!

Expose docker utils for re-use

---

plane/src/database/backend.rs
plane/src/proxy/route_map.rs

When a connection token does not exist, it was previously not being propagated to listeners (e.g. connections waiting on that route info response), which caused them to hang.

Fix invalid token issue

---

plane/src/controller/proxy.rs
plane/src/database/backend.rs

When a keepalive request fails because the backend has been removed, we should tell the proxy that the backend has been removed.
Fixes DIS-2106

Handle removed backend

---

docs/pages/concepts/backend-lifecycle.mdx
plane/src/controller/proxy.rs
plane/src/database/backend.rs
plane/src/drone/backend_manager.rs
plane/src/drone/executor.rs
plane/src/drone/state_store.rs
plane/src/log_types.rs
plane/src/types/backend_state.rs

Currently, we use `Terminating` to represent both soft and hard terminating. If a backend is hard-terminated while it is being soft-terminated (which is allowed), a backend goes from a `Terminating` state to another `Terminating` state. This is the only allowed state transition that does not move forward in the state sequence.
The change in this PR is to split soft- and hard- `Terminating` states into their own separate states. Soft-termination keeps the name `Terminating`, and hard termination gets `HardTerminating`. The field `termination` in `Terminating` remains, but is deprecated, and can only be set to `Soft` in the constructor.

Split `Terminating` into (soft) `Terminating` and `HardTerminating`

---

plane/src/typed_unix_socket/client.rs
plane/src/typed_unix_socket/mod.rs

The implementation had double retry loop bug, resulting in the timeout being irrelevant. Remove the outer retry loop and actually time out after 30 seconds. 
While we're at it, tune the backoff to be more reasonable (less spammy -- now retries quickly initially, then backs off significantly and slows down to 1 rps).

[bugfix] Prevent typed unix socket client from looping forever on failure to connect

---

plane/src/drone/backend_manager.rs
plane/src/types/backend_state.rs

https://github.com/jamsocket/plane/pull/766 introduced `BackendError::Other` as a way to handle misc errors that may occur in the `wait_for_backend()` executor function. However, the PR failed to handle that error type in `BackendManager`. As a result, spawns would succeed in spite of that error.
Introduce `TerminationReason::ErrorWaiting` and hard terminate any backend that encounters `BackendError::Other` in the `wait_for_backend()` step, logging the specifics. (Use a `match` statement to ensure future additions to the error struct get caught in this codepath during compilation.)

Handle `BackendError::Other` in `wait_for_backend()`

---

plane/src/drone/backend_manager.rs
plane/src/types/backend_state.rs

Renaming error status introduced in https://github.com/jamsocket/plane/pull/799 so that it's more user friendly.

Rename TerminationReason::ErrorWaiting => InternalError

---

docs/pages/concepts/architecture.mdx

If my understanding is correct, the proxy routes traffic to the session backend.
(Doesn’t the RouteMap manage routes on a per BearerToken basis?)
If my understanding is incorrect, please feel free to close this PR.

Improve description about proxy

---

Cargo.lock
plane/Cargo.toml
plane/plane-tests/Cargo.toml
plane/plane-tests/tests/common/auth_mock.rs
plane/plane-tests/tests/common/mod.rs
plane/plane-tests/tests/common/test_env.rs
plane/plane-tests/tests/forward_auth.rs
plane/src/controller/command.rs
plane/src/controller/forward_auth.rs
plane/src/controller/mod.rs

Adds `forward_auth` config option (name borrowed from [Caddy](https://caddyserver.com/docs/caddyfile/directives/forward_auth)). If provided, requests to `/ctrl/*` are forwarded to that URL first (after stripping the body). If that URL returns a 200, Plane proceeds; otherwise they are rejected.

Allow Plane to delegate auth

---

plane/plane-tests/tests/forward_auth.rs

Changes introduced in previous PR: https://github.com/jamsocket/plane/pull/804
Came up in GHA: https://github.com/jamsocket/plane/actions/runs/10625334742/job/29455134902

Fix clippy

---

plane/plane-tests/tests/docker_command.rs
plane/plane-tests/tests/health.rs
plane/src/client/mod.rs
plane/src/controller/mod.rs

We currently use `/ctrl/status` as a health check endpoint. The introduction of auth delegation (#804) applies, when enabled, to all `/ctrl` endpoints, including the health check. That means that the health checker needs to have credentials.
Instead, this adds a separate health check endpoint `/pub/health` which is part of the `/pub` path, which is not credentialed. This does not include the version information returned by the `/ctrl/status` endpoint, but does a health check.

Add health endpoint

---

plane/plane-tests/tests/backend_actions.rs
plane/plane-tests/tests/backend_lifecycle.rs
plane/plane-tests/tests/dns_api.rs
plane/plane-tests/tests/proxy_cert_lease.rs
plane/src/admin.rs
plane/src/controller/dns.rs
plane/src/controller/drone.rs
plane/src/controller/proxy.rs
plane/src/dns/mod.rs
plane/src/drone/mod.rs
plane/src/typed_socket/client.rs
plane/src/typed_socket/mod.rs
plane/src/typed_unix_socket/client.rs

What we know:
- Sometimes, when there are network issues, some (but not all) drones fail to reconnect. In the logs, it shows up as `failed to send heartbeat` (from [heartbeat.rs](https://github.com/jamsocket/plane/blob/afc9b7f0786f69770fb9fe4b9731fde566dc793d/plane/src/drone/heartbeat.rs#L19)), with the `err` value of `Disconnected` ([typed_socket](https://github.com/jamsocket/plane/blob/afc9b7f0786f69770fb9fe4b9731fde566dc793d/plane/src/typed_socket/mod.rs#L45)).
- When we “send” websocket messages, we are actually sending messages to a queue that gets picked up by the websocket event loop asynchronously. Disconnected [actually means that the message queue is full](https://github.com/jamsocket/plane/blob/afc9b7f0786f69770fb9fe4b9731fde566dc793d/plane/src/typed_socket/mod.rs#L51), which …

Improve typed socket connection robustness

---

README.md

Better discord link

---

Cargo.lock
plane/Cargo.toml
plane/plane-tests/Cargo.toml
plane/plane-tests/tests/common/localhost_resolver.rs
plane/plane-tests/tests/common/test_env.rs
plane/plane-tests/tests/forward_auth.rs
plane/src/client/sse.rs
plane/src/controller/connect.rs
plane/src/controller/error.rs
plane/src/controller/forward_auth.rs
plane/src/controller/mod.rs
plane/src/proxy/request.rs

Will be rebased after #814 is merged, but otherwise ready for eyes.

Update Axum version in proxy

---

docker/Dockerfile
docker/quickstart/Dockerfile

The dockerfiles need to be updated to account for `dynamic-proxy`.

Fix dockerfiles

---

Cargo.lock
plane/Cargo.toml
plane/src/main.rs

`rustls` requires a process-level `CryptoProvider` be setup. We already do this in `dynamic-proxy`, which is why those tests pass, but we do not do it in Plane itself so it sometimes fails.

Ensure that a process-level crypto provider exists

---

dynamic-proxy/src/proxy.rs
dynamic-proxy/tests/test_proxy_request.rs
plane/plane-tests/tests/proxy.rs

In the proxy, we currently use a timeout around the entire HTTP request. This does not only capture the time to make the initial connection as intended, but also the entire time of the request, which means that large requests fail.
This removes the timeout entirely, since the HTTP client has its own timeout that is aware of the connection status.

Remove timeout from HTTP request

---

plane/plane-tests/tests/cert_manager.rs
plane/src/proxy/cert_manager.rs
plane/src/proxy/cert_pair.rs

As part of the version updates we evidently lost the ability to parse pem files that have the heading `PRIVATE KEY` and instead need to specifically say `RSA PRIVATE KEY`.
Also, if we do fail, we should just fall back on ACME.

Fix private key parsing and add fallback on ACME

---

plane/src/proxy/cert_manager.rs

Although ACME accounts are essentially disposable, it's better to re-use them where possible, in particular when dealing with EAB (as we do with Google Certificate Manager), where an account can only be created once per EAB key set.
To date, we have done this eagerly by creating the ACME account when the Plane proxy process starts. The problem with this approach is that it creates an unnecessary point of failure when the ACME account fails to create but the proxy is otherwise ready to go.
This moves account creation into the refresh loop, but makes it lazy such that it only happens once per instance and then is remembered for future certificate refreshes. This way, if we start the proxy with a valid certificate already in place, it won't attempt to fetch the account immediately.

Fix proxy restart EAB issue

---

Cargo.lock
dynamic-proxy/Cargo.toml
dynamic-proxy/tests/common/hello_world_service.rs
dynamic-proxy/tests/common/simple_upgrade_service.rs
dynamic-proxy/tests/graceful.rs
dynamic-proxy/tests/graceful_https.rs
dynamic-proxy/tests/hello_world_http.rs
dynamic-proxy/tests/https_test.rs
dynamic-proxy/tests/test_http_redirect.rs
dynamic-proxy/tests/test_http_versions.rs
dynamic-proxy/tests/test_proxy_request.rs
dynamic-proxy/tests/test_proxy_websocket.rs
dynamic-proxy/tests/test_upgrade.rs
plane/Cargo.toml
plane/plane-tests/Cargo.toml
plane/plane-tests/tests/common/proxy_mock.rs
plane/plane-tests/tests/common/test_env.rs
plane/src/proxy/cert_manager.rs
plane/src/proxy/cert_pair.rs
plane/src/proxy/mod.rs
plane/src/proxy/proxy_server.rs
plane/src/proxy/request.rs

Version 0.5.0 was not published to crates.io because it depended on the repo-local crate `dynamic-proxy`.
This bumps the version to 0.5.1, and renames `dynamic-proxy` to `plane-dynamic-proxy` with the intent of publishing it as its own crate. (At least for now, I like this better than incorporating it in Plane, because it has its own test suite that we would have to co-mingle with Plane's if we were to merge them)

Version 0.5.1

---

plane/plane-dynamic/Cargo.toml
plane/plane-tests/Cargo.toml

When we only published one `plane` crate this didn't matter because we could do `cargo publish` by hand, but now that we have a couple published crates in the repo it's nice to be able to run `cargo ws publish` which requires this to be set.

Mark plane-tests and plane-dynamic as publish=false

---

docker/quickstart/Dockerfile

Same as #834, but for the quickstart dockerfile

Fix quickstart docker

---

Cargo.lock
dynamic-proxy/Cargo.toml
dynamic-proxy/src/connector.rs
dynamic-proxy/src/lib.rs
dynamic-proxy/src/proxy.rs
plane/plane-tests/tests/proxy.rs

We used to have a timeout on the lifespan of the entire request, which also captured an initial connection timeout, but also failed for long-lived connections like large requests. When we removed that timeout, we also removed the ability to time-out a request when the initial TCP connection hangs.
This adds back a timeout that only applies to the initial connection.

Add connection timeout

---

plane/src/drone/executor.rs
plane/src/drone/runtime/docker/mod.rs

We've observed failure modes where a container exit is not detected. In those cases, we expect that a termination request will see that the container is no longer running due to docker returning an error when calling `stop_container`/`kill_container`. Docker _doesn't_ error when calling `stop_container()` on an already stopped container, however. This has caused termination loops that never fully succeed, leaving the drone thinking the container is still running, and re-renewing its key over and over. This PR fixes this issue by checking the container's status before calling `terminate()` on it.
This still doesn't address these two issues, however:
(1) we aren't detecting the container exit in some cases which causes this failure mode in the first place
(2) we should make `terminating` …

drone failed to mark backend as terminated

---

docker/Dockerfile
docker/build-quickstart.sh
docker/quickstart/Dockerfile

Fix Plane docker builds

---

Cargo.lock
common/Cargo.toml
common/build.rs
dynamic-proxy/Cargo.toml
plane/Cargo.toml

If git is missing, the build script will fail. This changes it so that it uses the string `unknown` instead of the version.
This version is currently only used to log a warning if there is a version mismatch between the client and server. We should switch to using only the version number for this soon anyway now that the protocol is more stable.

Don't break build when git is missing

---

plane/src/proxy/route_map.rs

We weren't cleaning up tokio channels from the `listeners` map in the `RouteMap`. This may have been the source of a memory leak we've noticed in the proxies starting a few months back.

remove signaling channels from listeners once used

---

dynamic-proxy/src/server.rs

Ran locally and watched memory usage with `htop` while making a stream of requests to the proxy. Before this change, memory continued to increase with each request. After this change, memory rose slightly but then plateaued indefinitely.

fix mem leak - drop the JoinSets in the dynamic proxy connection loops

---

dynamic-proxy/src/body.rs
dynamic-proxy/src/request.rs
dynamic-proxy/tests/test_proxy_request.rs

We currently use `BoxBody` extensively, which [requires the body to be `Sync`](https://docs.rs/http-body-util/latest/http_body_util/combinators/struct.BoxBody.html), even though we don't actually rely on the `Body` being `Sync` in our code.
[Axum uses `UnsyncBoxBody`](https://docs.rs/axum-core/0.5.0/src/axum_core/body.rs.html#14) instead, which is like `BoxBody` but allows the contained body to be `!Sync`. So when we get a `Body` from Axum, we can't currently pass it to `dynamic_proxy` because it may not be `Sync`, even though our code doesn't actually care if it is `Sync`.
This replaces our use of `BoxBody` with `UnsyncBoxBody`.

Use `UnsyncBoxBody` instead of `BoxBody`
